version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data/downloads:/app/data/downloads
    environment:
      - DATABASE_URL=postgresql://webmonitor:webmonitor@db:5432/webmonitor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changethisinsecretkeytosomethingsecure
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data/downloads:/app/data/downloads
    environment:
      - DATABASE_URL=postgresql://webmonitor:webmonitor@db:5432/webmonitor
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changethisinsecretkeytosomethingsecure
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    command: python -m app.worker

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webmonitor
      - POSTGRES_PASSWORD=webmonitor
      - POSTGRES_DB=webmonitor
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 